// See the shakacode/shakapacker README and docs directory for advice on
// customizing your webpackConfig. The base config is generated by shakapacker
// from config/shakapacker.yml; merge customizations in here.
const { generateWebpackConfig } = require('shakapacker')
const webpack = require('webpack')

const webpackConfig = generateWebpackConfig()

// Expose jQuery globals ($) used by relationships/*.js.erb and the inline
// scripts in shared/_micropost_form.html.erb.
webpackConfig.plugins = webpackConfig.plugins || []
webpackConfig.plugins.push(
  new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery'
  })
)

module.exports = webpackConfig
